/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todas as categorias */
        get: operations["listCategorias"];
        put?: never;
        /** Cria uma nova categoria */
        post: operations["createCategoria"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorias/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atualiza uma categoria existente */
        put: operations["updateCategoria"];
        post?: never;
        /** Exclui uma categoria */
        delete: operations["deleteCategoria"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/produtos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todos os produtos com categoria aninhada */
        get: operations["listProdutos"];
        put?: never;
        /** Cria um novo produto */
        post: operations["createProduto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/produtos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atualiza um produto existente */
        put: operations["updateProduto"];
        post?: never;
        /** Exclui um produto */
        delete: operations["deleteProduto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CategoriaDto: {
            /** @example 1 */
            id: number;
            /** @example Eletronicos */
            nome: string;
            /** @example Produtos eletronicos diversos */
            descricao?: string | null;
        };
        CreateCategoriaDto: {
            /** @example Eletronicos */
            nome: string;
            descricao?: string | null;
        };
        UpdateCategoriaDto: {
            nome: string;
            descricao?: string | null;
        };
        ProdutoDto: {
            id: number;
            nome: string;
            descricao?: string | null;
            /** Format: double */
            preco: number;
            categoriaId: number;
            categoria: components["schemas"]["CategoriaDto"];
        };
        CreateProdutoDto: {
            nome: string;
            descricao?: string | null;
            /** Format: double */
            preco: number;
            categoriaId: number;
        };
        UpdateProdutoDto: {
            nome: string;
            descricao?: string | null;
            /** Format: double */
            preco: number;
            categoriaId: number;
        };
        ProblemDetails: {
            /** Format: uri */
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
        };
        ValidationProblemDetails: components["schemas"]["ProblemDetails"] & {
            /**
             * @example {
             *       "nome": [
             *         "O nome deve ter no mínimo 5 caracteres."
             *       ]
             *     }
             */
            errors?: {
                [key: string]: string[];
            };
        };
    };
    responses: {
        /** @description Erro de validacao no payload */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblemDetails"];
            };
        };
        /** @description Recurso nao encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        IdPathParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCategorias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de categorias */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"][];
                };
            };
        };
    };
    createCategoria: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoriaDto"];
            };
        };
        responses: {
            /** @description Categoria criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"];
                };
            };
            400: components["responses"]["ValidationProblem"];
        };
    };
    updateCategoria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoriaDto"];
            };
        };
        responses: {
            /** @description Atualizado com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationProblem"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCategoria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excluido com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Categoria possui produtos vinculados */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.8",
                     *       "title": "Conflict",
                     *       "status": 409,
                     *       "detail": "Não é possível excluir uma categoria que possua produtos vinculados."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listProdutos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de produtos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProdutoDto"][];
                };
            };
        };
    };
    createProduto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProdutoDto"];
            };
        };
        responses: {
            /** @description Produto criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProdutoDto"];
                };
            };
            400: components["responses"]["ValidationProblem"];
        };
    };
    updateProduto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProdutoDto"];
            };
        };
        responses: {
            /** @description Atualizado com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationProblem"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteProduto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excluido com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
}
